export enum ClassifierType {
  BAYES = 'BAYES',
  LOGISTIC_REGRESSION = 'LOGISTIC_REGRESSION',
  APPARATUS_LOGISTIC_REGRESSION = 'APPARATUS_LOGISTIC_REGRESSION',
  APPARATUS_BAYES = 'APPARATUS_BAYES'
}